# Generated by Django 5.1.2 on 2024-10-19 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_multiple_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='online_backup',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No internet service', 'No internet service'), ('No', 'No')], default='No', max_length=20),
        ),
    ]
